import React, { useState } from 'react';
import { ProjectItem } from '../../types/project';
import { useTranslation } from '../../i18n/useTranslation';
import { openInEditor } from '../../utils/editorLauncher';
import { X, Copy, Check, Download, FileCode, ExternalLink, Sparkles } from 'lucide-react';

interface ProjectReadmeModalProps {
  project: ProjectItem;
  isOpen: boolean;
  onClose: () => void;
}

export const ProjectReadmeModal: React.FC<ProjectReadmeModalProps> = ({
  project,
  isOpen,
  onClose,
}) => {
  const { language } = useTranslation();
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const mermaidChart = `\`\`\`mermaid
graph TD
    Client["🌐 Client / UI Tier (${project.stack.filter((s) => ['React', 'Next.js', 'Vue.js', 'Flutter'].includes(s)).join(', ') || 'TypeScript UI'})"] --> API["⚡ Core Engine / Service Layer"]
    API --> AI["🤖 Agent & Model Orchestration"]
    AI --> Storage["💾 Persistence & State Management"]
    API --> Telemetry["📊 GitHub Actions CI/CD & Playwright"]
\`\`\``;

  const generatedReadme = `# ${project.name}

> ${project.description}

[![VibeOS Score](https://img.shields.io/badge/VibeOS_Score-${project.score.total}%2F100-06B6D4?style=flat-square&logo=visualstudiocode)](https://hkjang.github.io/VibeOS/)
[![Stage](https://img.shields.io/badge/Stage-${project.stage.toUpperCase()}-10B981?style=flat-square)](https://github.com/hkjang/${project.name})
[![Tech Stack](https://img.shields.io/badge/Stack-${encodeURIComponent(project.stack.join(' | '))}-8B5CF6?style=flat-square)](https://github.com/hkjang/${project.name})

---

## 🌟 Overview & Purpose

\`${project.name}\` is an engineering solution developed by [@hkjang](https://github.com/hkjang).
- **Lifecycle Stage**: \`${project.stage.toUpperCase()}\`
- **4D AI Score**: **${project.score.total}/100** (Activity: ${project.score.activity}, Potential: ${project.score.potential}, Reuse: ${project.score.reuse}, Maintainability: ${project.score.maintainability})
- **Architecture Pattern**: \`${project.dna.architecture}\`

---

## 🏗️ System Architecture Topology

${mermaidChart}

---

## 🛠️ Key Technologies & Dependencies

| Category | Details |
| :--- | :--- |
| **Languages & Frameworks** | \`${project.stack.join('`, `')}\` |
| **Commit Momentum** | ${project.dna.commitVelocityWeekly} commits / week |
| **Key Architecture Patterns** | \`${project.dna.keyPatterns.join('`, `')}\` |
| **Local Workspace Path** | \`/mnt/d/project/${project.name}\` |

---

## 🚀 Quick Setup & Local Execution

\`\`\`bash
# 1. Clone repository
git clone ${project.dna.githubUrl}.git
cd ${project.name}

# 2. Install dependencies
npm install # or pnpm install / yarn

# 3. Start local development server
npm run dev
\`\`\`

---

## 🎯 Next Recommended Milestone

- **AI Action Item**: ${project.nextAction}
- **Category**: \`${project.nextActionCategory.toUpperCase()}\`

---
*Generated by [VibeOS](https://github.com/hkjang/VibeOS) — Operating System for Vibe Coders.*
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedReadme);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([generatedReadme], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project.name}-README.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-fadeIn">
      <div className="relative w-full max-w-3xl rounded-3xl bg-[#090D16] border border-slate-800 shadow-2xl overflow-hidden flex flex-col max-h-[85vh]">
        {/* Header */}
        <div className="p-4 sm:p-5 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2 text-cyan-400">
            <FileCode className="w-5 h-5" />
            <h2 className="text-sm sm:text-base font-bold text-white font-mono">
              AI Production README.md Generator — {project.name}
            </h2>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg text-slate-400 hover:text-white">
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 p-4 sm:p-6 overflow-y-auto font-mono text-xs text-slate-300 bg-slate-900/50">
          <pre className="whitespace-pre-wrap leading-relaxed">{generatedReadme}</pre>
        </div>

        {/* Footer */}
        <div className="p-4 bg-slate-950 border-t border-slate-800 flex items-center justify-between gap-3 flex-wrap">
          <button
            onClick={() => openInEditor(project.name, 'vscode')}
            className="flex items-center gap-1.5 text-xs text-cyan-400 hover:underline font-mono"
          >
            <ExternalLink className="w-3.5 h-3.5" />
            <span>Open in VS Code (`/mnt/d/project/${project.name}`)</span>
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-slate-800 text-slate-200 hover:bg-slate-700 text-xs font-bold font-mono transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy README'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-cyan-500 text-slate-950 hover:bg-cyan-400 text-xs font-bold font-mono transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download README.md</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
